version: "3.7"

services:
  goland:
    build:
      context: ./docker/goland
    container_name: 'goland'
    ports:
      - "3333:3333"
    links:
      - elasticsearch
    volumes:
      - ./api:/go/src/github.com/GoElasticsearch/api
  elasticsearch:
    build: ./docker/elasticsearch
    container_name: 'elasticsearch'
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - ./srv/elas1:/usr/share/elasticsearch/data
    networks:
      - esnet

networks:
  esnet:
    driver: bridge